# Run using docker, not a VM
sudo: false

language: c
compiler: clang

before_install:
    - sudo apt-get -y install libjpeg-dev clang-tidy libv4l-dev

install:
    - cmake

script: 
    - ./build.sh

deploy:
    provider: releases
    skip_cleanup: true
    on:
        tags: true
    file: 
        - build/x86/bin/*
        - build/x86/lib/*
    api_key:
        secure: "bVNtp4SAm2W8RjvVZtYESuCKuQmn84RI0ZBbPedJDET1hdULTfe1XiLvUyMJJxILT4bhsjR0a48xRE6tluKuFNwTdpdRzykSi2lfdkny3x9KomqRcTfMeztARHSV1qbDJxZJRxduYjblDRRM5J2ANfNAyzNJxEy3JktFSpBfFwNUTbB6CU9Kb/2AcCwHmS17Zd8hQKr+bLQ6wM4Eg3YSI7Lce0CJWtYqrm6vK9+kjfSDqIPz8ExLqMAYxWCjpZfrfKGDWkwH6gFUpeP+VlEVF9ReuUhlC0TlmNxChFhOWiQn3dkiMzSlPqnHb6FdcvA09yEQwtFSpec3qH9yk7yD145347xzp2W6y42XNctSxhtXmAaqn/m84xUrv0pkuvAjKB3+PwfNDFxpHKvDrne07WRD7wjX2eAaOzpiPrlH8dEu2OXQq+koZ9XZ0c+xriU0Bbq34xbkMmL85T6AAcJ1JG6JJfcw/xk3z4qrgSVwSDYlrGtT8g2OrOKj4PXJWe05CkBfx3QFz3qqx4EZoV1Ksb7MlhSSiskmb4A8RlIuP5MXc8NQP3rHhbP8SNi/8E7Hjo62hHC2ThWl5qJ/xJu9RqsIF9Oxmx1UIg75wCXiz6fU9wXnFu+Mdwd0py83h9J15wLZjGBmTvCDsMmOs0U7kp9rRU+pf+RZeOMgA00A6XY="
